server:
  port: 8082
spring:
  application:
    name: inventory-service
  h2:
    console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:inventory_db
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect